meta_product_name: "Cloud Castles"
meta_title: "Cloud Castles - Live Like Royalty"
meta_description: "The castles, mansions, and palaces of your dreams"
meta_image: "eltz02.jpg" # should exist in `app/assets/images/`
